<?php
/**
 * VAPT Security - Domain Locked Configuration
 * 
 * This file is automatically generated by VAPT Security.
 * It is locked to the domain pattern: hermasnet
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: a0d33be2861ab0331f9b86c0e0d66766f4608503d1857fb5b8059cff117e93fd
 */

$vapt_locked_config_data = '{\"domain_pattern\":\"hermasnet\",\"settings\":[],\"generated_at\":1766303673,\"generated_by\":\"tanmalik786\"}';
$vapt_locked_config_sig = 'a0d33be2861ab0331f9b86c0e0d66766f4608503d1857fb5b8059cff117e93fd';
