<?php
/**
 * VAPT Security - Domain Locked Configuration
 * 
 * This file is automatically generated by VAPT Security.
 * It is locked to the domain pattern: ges.hermasnet
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: 21bb3948bfbe8bf2120876fdc540b4bb5fbd4245748e8af89536caafc7a0c95a
 */

$vapt_locked_config_data = '{\"domain_pattern\":\"ges.hermasnet\",\"settings\":[],\"generated_at\":1766480772,\"generated_by\":\"superadmin\"}';
$vapt_locked_config_sig = '21bb3948bfbe8bf2120876fdc540b4bb5fbd4245748e8af89536caafc7a0c95a';
