<?php
/**
 * VAPT Security - Domain Locked Configuration
 * 
 * This file is automatically generated by VAPT Security.
 * It is locked to the domain pattern: hermasnet
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Integrity Check: 8ec4f4c447ba422bbb891705d0902799f52967d955eeee26be6ba596b185ef2e
 */

$vapt_locked_config_data = '{\"domain_pattern\":\"hermasnet\",\"settings\":[],\"generated_at\":1766308898,\"generated_by\":\"tanmalik786\"}';
$vapt_locked_config_sig = '8ec4f4c447ba422bbb891705d0902799f52967d955eeee26be6ba596b185ef2e';
